### ISSUE TITLE
Changing DRAM Timing Cfg in CbsSetup soft broke the device

### ISSUE THREAD

**Issue by emptyset0** [SmokelessCPU/UniversalAMDFormBrowser#3]
Thanks for your amazing work!
I tried it on my HP Omen 16-cxxx with 5800H.
It could modify 1T/2T and GDM settings successfully.
However, the device just didn't boot after I toggled "Overclock" in "DRAM Timing Configuration" in CbsSetup from "Auto" to "Enabled", even if anything under it remained "Auto". (Recovered after resetting CMOS by plugging off the battery cable.)
I think it might be a special case that HP blocked it?
Here is the BIOS file. There is an option to extract it after running the update executable.
https://support.hp.com/us-en/drivers/selfservice/swdetails/omen-16.1-inch-gaming-laptop-pc-16-c0000/2100371407/swItemId/ob-291599-1

**Comment by SmokelessCPU** [comment]
From my experience Seem that ram OC through CBS, don't work on 5800H, also on Legion 5/5Pro, has the same behavior's

The real Ram OC in Zen3 is the AMD overclocking menu, but this sadly, is not available on non HX Cpu

**Comment by emptyset0** [comment]
I saw someone posted that he changed memory timings through CBS successfully on his on Legion 5 Pro with 5800h using your tool. He said the memory frequency couldn't be set above 1600mhz (ddr4 3200), but the memory timings could be tightened. I don't know whether it works on your Legion 5/5 Pro though. :D

**Comment by SmokelessCPU** [comment]
@emptyset0 Can you link that post?

I have a 2020 Legion 4800H so I have no problem with ram timing, but all guy on Legion Series and Laptop Wiki Server that tried changing the timing, reported unable to boot...
The only difference that we did unlocking the native bios, but this should be irrelevant

**Comment by emptyset0** [comment]
The post is on a Chinese forum. The author said he succeeded to modify the memory timings with this tool after updating to the newest BIOS. (Yes, he had used your unlocker to unlock the BIOS before Lenovo patched it.)
He uploaded a screenshot of AIDA and didn't showed much details. The screenshot doesn't contain the memory timings (maybe in safe mode) but the latency is quite low.
I've asked him for details, and I'll post here as long as he reply to me.
![9aQ2q-k4i9ZaT3cSty-ss](https://user-images.githubusercontent.com/16044351/173194279-a65f8b27-df0e-4661-a543-4eff1796b9b8.jpg)

**Comment by emptyset0** [comment]
I am sorry that I made a mistake.
He flashed SPD to modify timings and used this tool just to disable GDM and enable 1T.
Sorry again for misleading you. Issue closed.
